app:
  port: 8080

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: notifications

kafka:
  brokers:
    - "localhost:9092"
  group_id: "notification-consumer"
  topics:
    - "service_1_events"
    - "service_2_events"
    - "service_3_events"
    - "service_4_events"
    - "service_5_events"

email:
  api_key: ""
  from: "your_email@example.com"
